1 start
evgenmil/dz-react pull request #1
Opened 2024-03-28 12:06 UTC by evgenmil

2024-03-30 09:31 UTC, evgenmil commented
@Webappmaster-Eugene Приветствую, нужно ли дополнительно уведомлять в выполнении ДЗ в ТГ чате, или работы проверяются только в конце курса? Спасибо

2024-04-09 04:30 UTC, Webappmaster-Eugene requested changes
Поправим недочеты и в путь!)

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/App.jsx
> +const INITIAL_DATA_FILMS = [
Стоит вынести в отдельную константу в отдельном файле с константами

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/App.jsx
> +import { useState } from 'react';
Напишу здесь - НО касается всех css файлов проекта. Понимаю, что пользовались плагином, позволяющим импортить значения из фигмы, но читать на проде - это невозможно и сразу ставит крест на рефакторинге.
font-size: 1rem;
line-height: 150%;
letter-spacing: 0.02em;
Не буду придираться сейчас, но в будущем - заставлю переделать. И вообще это фу) Лучше в пикселях, как на макете.

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/components/Paragraph/Paragraph.jsx
> +export default function Paragraph(props) {
Советую сразу декомпозировать пропсы - вот так {className, children, ...props
}

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/components/NavBar/NavBar.jsx
> +			<a href='' className='active'>Поиск фильмов</a>
В будущем можно создать отдельный компонент для ссылки Link

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/components/Icon/Icon.jsx
> +	const src = '/' + name;
лучше сразу передавать путь, а не только имя. Изображения могут располагаться не только в корне('./'), но и где-то во внешнем хранилище например. Такая обработка файлов неочивидна. В таком случае можете назвать пропс srcImage и его значение сразу вставлять в <img src=>

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/components/H1/H1.css
> +  letter-spacing: -0.02em;
Жесть)

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/components/CardList/CardList.jsx
> +	return <div className='card-list'>{itemsList}</div>;
Все верно обработано +

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/components/CardLink/CardLink.jsx
> +	return <a onClick={onClick} className={cl}>{icon} {label}</a>;
а где href?

2024-04-09 04:30 UTC, Webappmaster-Eugene commented on src/components/CardLink/CardLink.jsx
> +	const cl = 'add-card-link ' + (className || '');
Стоит переписать через шаблонную строчку и тернарную операцию className ? \`add-card-link ${className}\` : add-card-link '

2024-04-09 11:43 UTC, evgenmil commented
@Webappmaster-Eugene все правки внёс

2024-04-09 11:58 UTC, evgenmil commented on src/components/CardLink/CardLink.jsx
> +	const cl = 'add-card-link ' + (className || '');
исправил

2024-04-09 11:58 UTC, evgenmil commented on src/components/CardLink/CardLink.jsx
> +	return <a onClick={onClick} className={cl}>{icon} {label}</a>;
добавил

2024-04-09 11:58 UTC, evgenmil commented on src/components/CardList/CardList.jsx
> +	return <div className='card-list'>{itemsList}</div>;
сэнкс

2024-04-09 11:58 UTC, evgenmil commented on src/components/H1/H1.css
> +  letter-spacing: -0.02em;
удалил em и заменил rem на px

2024-04-09 11:58 UTC, evgenmil commented on src/components/Icon/Icon.jsx
> +	const src = '/' + name;
сделал

2024-04-09 11:59 UTC, evgenmil commented on src/components/NavBar/NavBar.jsx
> +			<a href='' className='active'>Поиск фильмов</a>
ок

2024-04-09 11:59 UTC, evgenmil commented on src/components/Paragraph/Paragraph.jsx
> +export default function Paragraph(props) {
готово

2024-04-09 11:59 UTC, evgenmil commented on src/App.jsx
> +import { useState } from 'react';
ок, принял

2024-04-09 11:59 UTC, evgenmil commented on src/App.jsx
> +const INITIAL_DATA_FILMS = [
сделал

2024-04-10 20:15 UTC, Webappmaster-Eugene reviewed
Отлично!

2024-04-10 20:15 UTC, merged